version: "3.8"
services:
  api:
    image: "budhiarta/capstone-15:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db_main
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstone
    networks:
      - db_main
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  db_main:
    driver: bridge